# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyPortfolio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyPortfolio
  

end

target 'MyPortfolio-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyPortfolio-tvOS

  target 'MyPortfolio-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
